### ISSUE TITLE
Help configuring

### ISSUE THREAD

**Issue by costispavlou** [fisherwise/homebridge-soma-shades#1]
I've installed the package and the bluetooth libraries, but where to next? 
can you help as I don't know where to find the mac addresses of my soma devices.

**Comment by costispavlou** [comment]
12/15/2020, 10:45:20 PM [SOMAShades] Initializing SOMAShades platform...
12/15/2020, 10:45:20 PM Loading 3 accessories...

            "platform": "SOMAShades",
            "plugin_map": {
                "plugin_name": "homebridge-soma-shades"
            },
            "devices": [
                {
                    "name": "Venetian Blind",
                    "id": "eef039b336ca"
                },
                {
                    "name": "Venetian Tilt",
                    "id": "f4925f0aed00"
                },
                {
                    "name": "Bedroom Shade",
                    "id": "f463adb3ad1a"
                }
            ]

**Comment by oovz** [comment]
Hi! You can find your soma device mac in the Smart Shades App.
Looks like you've configured them

**Comment by costispavlou** [comment]
I cant see them on homekit though.

**Comment by oovz** [comment]
> I cant see them on homekit though.

can you try restart the homebridge in debug mode, (preferablly disable all other plugins), and paste the complete logs here?

**Comment by costispavlou** [comment]
i restarted numerous times. no change.

**Comment by oovz** [comment]
can you paste logs here

**Comment by costispavlou** [comment]
![image](https://user-images.githubusercontent.com/57916603/102322733-327bac00-3f88-11eb-8234-635429966c8c.png)

**Comment by oovz** [comment]
can you wait 30 seconds and paste the full log with homebridge in DEBUG mode?

**Comment by costispavlou** [comment]
can you help me figure out how to do that in hoobs?

**Comment by costispavlou** [comment]
12/16/2020, 9:59:26 AM [TuyaWebPlatform] [Bedroom Shutter] Characteristic.On - [GET] 3
12/16/2020, 10:21:36 AM [Roborock] INF getCleaning | roborock.vacuum.s5 | Cleaning is false
12/16/2020, 10:21:36 AM [Roborock] INF getCareSensors | roborock.vacuum.s5 | Sensors dirtytime is 104260 seconds / 96.54%.
12/16/2020, 10:21:36 AM [Roborock] INF getCareFilter | roborock.vacuum.s5 | Filter worktime is 240429 seconds / 44.52%.
12/16/2020, 10:21:36 AM [Roborock] INF getCareSideBrush | roborock.vacuum.s5 | Sidebrush worktime is 240429 seconds / 33.39%.
12/16/2020, 10:21:36 AM [Roborock] INF getCareSensors | roborock.vacuum.s5 | Sensors dirtytime is 104260 seconds / 96.54%.
12/16/2020, 10:21:36 AM [Roborock] INF getCareFilter | roborock.vacuum.s5 | Filter worktime is 240429 seconds / 44.52%.
12/16/2020, 10:21:36 AM [Roborock] INF getCareSideBrush | roborock.vacuum.s5 | Sidebrush worktime is 240429 seconds / 33.39%.
12/16/2020, 10:21:36 AM [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 104 over miIO. Converting to HomeKit
12/16/2020, 10:21:36 AM [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 104 over miIO "Max" > HomeKit speed 100%
12/16/2020, 10:21:36 AM [Roborock] INF getCharging | roborock.vacuum.s5 | Charging is true (Status is charging)
12/16/2020, 10:21:36 AM [Roborock] INF getBattery | roborock.vacuum.s5 | Batterylevel is 100%
12/16/2020, 10:21:36 AM [Roborock] INF getBatteryLow | roborock.vacuum.s5 | Batterylevel is 100%
12/16/2020, 10:21:36 AM [Roborock] INF getDocked | roborock.vacuum.s5 | Robot Docked is true (Status is charging)
12/16/2020, 10:21:36 AM [Roborock] INF getCareSensors | roborock.vacuum.s5 | Sensors dirtytime is 104260 seconds / 96.54%.
12/16/2020, 10:21:36 AM [Roborock] INF getCareSensors | roborock.vacuum.s5 | Sensors dirtytime is 104260 seconds / 96.54%.
12/16/2020, 10:21:36 AM [Roborock] INF getCareFilter | roborock.vacuum.s5 | Filter worktime is 240429 seconds / 44.52%.
12/16/2020, 10:21:36 AM [Roborock] INF getCareFilter | roborock.vacuum.s5 | Filter worktime is 240429 seconds / 44.52%.
12/16/2020, 10:21:36 AM [Roborock] INF getCareSideBrush | roborock.vacuum.s5 | Sidebrush worktime is 240429 seconds / 33.39%.
12/16/2020, 10:21:36 AM [Roborock] INF getCareSideBrush | roborock.vacuum.s5 | Sidebrush worktime is 240429 seconds / 33.39%.
12/16/2020, 10:21:36 AM [Roborock] INF getCareMainBrush | roborock.vacuum.s5 | Mainbrush worktime is 240429 seconds / 22.26%.
12/16/2020, 10:21:36 AM [Roborock] INF getCareMainBrush | roborock.vacuum.s5 | Mainbrush worktime is 240429 seconds / 22.26%.
12/16/2020, 10:21:36 AM [TuyaWebPlatform] [Boiler Switch] - Requesting device state
12/16/2020, 10:21:36 AM [TuyaWebPlatform] [Boiler Switch] - Creating new debounced promise
12/16/2020, 10:21:36 AM [TuyaWebPlatform] [Boiler Switch] - Triggering debouncedDeviceStateRequest
12/16/2020, 10:21:36 AM [TuyaWebPlatform] [Office Shutter] - Requesting device state
12/16/2020, 10:21:36 AM [TuyaWebPlatform] [Office Shutter] - Creating new debounced promise
12/16/2020, 10:21:36 AM [TuyaWebPlatform] [Office Shutter] - Triggering debouncedDeviceStateRequest
12/16/2020, 10:21:36 AM [TuyaWebPlatform] [Bedroom Shutter] - Requesting device state
12/16/2020, 10:21:36 AM [TuyaWebPlatform] [Bedroom Shutter] - Creating new debounced promise
12/16/2020, 10:21:36 AM [TuyaWebPlatform] [Bedroom Shutter] - Triggering debouncedDeviceStateRequest
12/16/2020, 10:21:36 AM [TuyaWebPlatform] [Boiler Switch] - Unsetting debouncedDeviceStateRequestPromise
12/16/2020, 10:21:36 AM [TuyaWebPlatform] [Office Shutter] - Unsetting debouncedDeviceStateRequestPromise
12/16/2020, 10:21:36 AM [TuyaWebPlatform] [Bedroom Shutter] - Unsetting debouncedDeviceStateRequestPromise
12/16/2020, 10:21:37 AM [TuyaWebPlatform] [Bedroom Shutter] - Set device state request cache
12/16/2020, 10:21:37 AM [TuyaWebPlatform] [Bedroom Shutter] - Resolving resolveDeviceStateRequest from remote
12/16/2020, 10:21:37 AM [TuyaWebPlatform] [Bedroom Shutter] Characteristic.On - [GET] 3
12/16/2020, 10:21:37 AM [TuyaWebPlatform] [Office Shutter] - Renewing cache due to RateLimitError
12/16/2020, 10:21:37 AM [TuyaWebPlatform] [Office Shutter] Characteristic.On - [GET] 3
12/16/2020, 10:21:37 AM [TuyaWebPlatform] [Boiler Switch] - Set device state request cache
12/16/2020, 10:21:37 AM [TuyaWebPlatform] [Boiler Switch] - Resolving resolveDeviceStateRequest from remote
12/16/2020, 10:21:37 AM [TuyaWebPlatform] [Boiler Switch] Characteristic.On - [GET] false
12/16/2020, 10:21:37 AM [Roborock] INF getCleaning | roborock.vacuum.s5 | Cleaning is false
12/16/2020, 10:21:37 AM [Roborock] INF getCareSensors | roborock.vacuum.s5 | Sensors dirtytime is 104260 seconds / 96.54%.
12/16/2020, 10:21:37 AM [Roborock] INF getCareFilter | roborock.vacuum.s5 | Filter worktime is 240429 seconds / 44.52%.
12/16/2020, 10:21:37 AM [Roborock] INF getCareSideBrush | roborock.vacuum.s5 | Sidebrush worktime is 240429 seconds / 33.39%.
12/16/2020, 10:21:37 AM [Roborock] INF getCareSensors | roborock.vacuum.s5 | Sensors dirtytime is 104260 seconds / 96.54%.
12/16/2020, 10:21:37 AM [Roborock] INF getCareFilter | roborock.vacuum.s5 | Filter worktime is 240429 seconds / 44.52%.
12/16/2020, 10:21:37 AM [Roborock] INF getCareSideBrush | roborock.vacuum.s5 | Sidebrush worktime is 240429 seconds / 33.39%.
12/16/2020, 10:21:37 AM [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 104 over miIO. Converting to HomeKit
12/16/2020, 10:21:37 AM [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 104 over miIO "Max" > HomeKit speed 100%
12/16/2020, 10:21:37 AM [Roborock] INF getCharging | roborock.vacuum.s5 | Charging is true (Status is charging)
12/16/2020, 10:21:37 AM [Roborock] INF getBattery | roborock.vacuum.s5 | Batterylevel is 100%
12/16/2020, 10:21:37 AM [Roborock] INF getBatteryLow | roborock.vacuum.s5 | Batterylevel is 100%
12/16/2020, 10:21:37 AM [Roborock] INF getDocked | roborock.vacuum.s5 | Robot Docked is true (Status is charging)
12/16/2020, 10:21:37 AM [Roborock] INF getCareSensors | roborock.vacuum.s5 | Sensors dirtytime is 104260 seconds / 96.54%.
12/16/2020, 10:21:37 AM [Roborock] INF getCareSensors | roborock.vacuum.s5 | Sensors dirtytime is 104260 seconds / 96.54%.
12/16/2020, 10:21:37 AM [Roborock] INF getCareFilter | roborock.vacuum.s5 | Filter worktime is 240429 seconds / 44.52%.
12/16/2020, 10:21:37 AM [Roborock] INF getCareFilter | roborock.vacuum.s5 | Filter worktime is 240429 seconds / 44.52%.
12/16/2020, 10:21:37 AM [Roborock] INF getCareSideBrush | roborock.vacuum.s5 | Sidebrush worktime is 240429 seconds / 33.39%.
12/16/2020, 10:21:37 AM [Roborock] INF getCareSideBrush | roborock.vacuum.s5 | Sidebrush worktime is 240429 seconds / 33.39%.
12/16/2020, 10:21:37 AM [Roborock] INF getCareMainBrush | roborock.vacuum.s5 | Mainbrush worktime is 240429 seconds / 22.26%.
12/16/2020, 10:21:37 AM [Roborock] INF getCareMainBrush | roborock.vacuum.s5 | Mainbrush worktime is 240429 seconds / 22.26%.
12/16/2020, 10:21:37 AM [TuyaWebPlatform] [Boiler Switch] - Requesting device state
12/16/2020, 10:21:37 AM [TuyaWebPlatform] [Boiler Switch] - Creating new debounced promise
12/16/2020, 10:21:37 AM [TuyaWebPlatform] [Boiler Switch] - Triggering debouncedDeviceStateRequest
12/16/2020, 10:21:37 AM [TuyaWebPlatform] [Office Shutter] - Requesting device state
12/16/2020, 10:21:37 AM [TuyaWebPlatform] [Office Shutter] - Creating new debounced promise
12/16/2020, 10:21:37 AM [TuyaWebPlatform] [Office Shutter] - Triggering debouncedDeviceStateRequest
12/16/2020, 10:21:37 AM [TuyaWebPlatform] [Bedroom Shutter] - Requesting device state
12/16/2020, 10:21:37 AM [TuyaWebPlatform] [Bedroom Shutter] - Creating new debounced promise
12/16/2020, 10:21:37 AM [TuyaWebPlatform] [Bedroom Shutter] - Triggering debouncedDeviceStateRequest
12/16/2020, 10:21:38 AM [TuyaWebPlatform] [Boiler Switch] - Unsetting debouncedDeviceStateRequestPromise
12/16/2020, 10:21:38 AM [TuyaWebPlatform] [Boiler Switch] - Resolving resolveDeviceStateRequest from cache
12/16/2020, 10:21:38 AM [TuyaWebPlatform] [Boiler Switch] Characteristic.On - [GET] false
12/16/2020, 10:21:38 AM [TuyaWebPlatform] [Office Shutter] - Unsetting debouncedDeviceStateRequestPromise
12/16/2020, 10:21:38 AM [TuyaWebPlatform] [Office Shutter] - Resolving resolveDeviceStateRequest from cache
12/16/2020, 10:21:38 AM [TuyaWebPlatform] [Office Shutter] Characteristic.On - [GET] 3
12/16/2020, 10:21:38 AM [TuyaWebPlatform] [Bedroom Shutter] - Unsetting debouncedDeviceStateRequestPromise
12/16/2020, 10:21:38 AM [TuyaWebPlatform] [Bedroom Shutter] - Resolving resolveDeviceStateRequest from cache
12/16/2020, 10:21:38 AM [TuyaWebPlatform] [Bedroom Shutter] Characteristic.On - [GET] 3

**Comment by oovz** [comment]
sorry I'm not familiar with hoobs. In homebridge I can turn debug mode on using homebridge-config-ui-x.
there's nothing from ```SOMAShades``` in your log and I'm guess the debug mode is not on. Can you try turn the debug mode on as it will give more information for diagnostics.

**Comment by costispavlou** [comment]
there's no option for debug for hoobs.
the service needs to be stopped and the terminal cannot be accessed for debug without that service.
in any case. somashades can be seen on the log above, where i highlighted

**Comment by oovz** [comment]
that 2 lines are not enough to diagnose anything

**Comment by oovz** [comment]
I'm closing this as there's no new info. You can re-open it if you're still having issues with it.

**Comment by costispavlou** [comment]
Hey @fisherwise. Sorry for the delay. I have no info cause I cannot debug this on hoobs. Either your app is not working on hoobs, or there's something i'm terribly doing wrong. Do I need to add a bluetooth usb dongle on my raspberry pi? Is there any other way I can try this out? Should I download homebridge on my computer and try setting it up from there?
