### ISSUE TITLE
Some files not available while installing Bluetooth libraries

### ISSUE THREAD

**Issue by hasnaink786** [fisherwise/homebridge-soma-shades#3]
**Describe Your Problem:**

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**
![0589F5F2-71CD-4732-B695-FB1ECBD2D702](https://user-images.githubusercontent.com/76628720/103161656-20cdac00-47b3-11eb-93b5-9c0a9dde0a26.png)

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by oovz** [comment]
looks like your repo doesn't have the packages we need. you can try
1. run ```sudo apt update``` then try again
2. configure raspbian to use another repo. more details here: [link](https://www.raspbian.org/RaspbianRepository)

**Comment by oovz** [comment]
I'm closing this as there's no new info. You can re-open it if you're still having issues with it.
