### ISSUE TITLE
Plug-in not running

### ISSUE THREAD

**Issue by psdc-create** [fisherwise/homebridge-soma-shades#6]
I can't get the plug-in to do anything. I believe the error is related to this message I get when I restart home bridge:

"noble warning: adapter state unauthorized, please run as root or with sudo
               or see README for information on running without root/sudo:
               https://github.com/sandeepmistry/noble#running-on-linux
[5/10/2021, 5:16:21 AM] [SOMAShades] noble is not running. waiting for it to power on..."

I'm out of ideas!

**Environment:**

* **Plugin Version**: Current
* **Homebridge Version**: Current
* **Node.js Version**: Unsure
* **NPM Version**:  current
* **Operating System**:

**Comment by oovz** [comment]
Have you tried to add necessary permissions described in that link?

**Comment by psdc-create** [comment]
If you mean this section of the linked file:

Make sure node is on your PATH. If it's not, some options:

Symlink nodejs to node: sudo ln -s /usr/bin/nodejs /usr/bin/node
Install Node.js using the NodeSource package

I've tried the first option with no luck (symlink Command not found). Oddly enough "man symlink" returns an entry. Sorry - I'm new to the pi and these soma shades are doing my head in. I've been trying to link them to HomeKit for days.

**Comment by oovz** [comment]
what system you're running? I've not heard of any linux system not having ```ln```
anyway you should checking this section https://github.com/abandonware/noble#running-without-rootsudo-linux-specific

**Comment by psdc-create** [comment]
Thanks so much for your replies. I appreciate your time.

The link takes me to:

sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)
What I don't follow is this part of the command "$(eval readlink -f `which node`)”

I’ve tried a few options but no change.

I do wonder if my problems are because I’m running homebridge in a docker container?

Otherwise I’ve updated node to the most recent version and the same with noble. I think my rasperian installation is a new install (only reinstalled 3 days ago).

If it’s a container problem then it’s not really a bug…

Thanks again.

**Comment by oovz** [comment]
not sure what you mean by ```$(eval readlink -f `which node`)```. it should return you the path of node executable (in this case /usr/bin/node)
I haven't tried running homebridge in a docker container so I can't offer much help here. I would assume you need extra steps to pass bluetooth device into container

**Comment by psdc-create** [comment]
This is where things might be going astray - 'which node’ returns /home/pi/n/bin/node

Would this be the reason I cant get the plug-in to run.

**Comment by oovz** [comment]
are you installing nodejs this [way](https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian#step-1-install-nodejs)?
still i would guess there are extra steps to "pass" bluetooth device into a docker container. Maybe try this command and see if you have bluetooth device: ```hcitool dev```

**Comment by psdc-create** [comment]
Solved!

There are many discussions on the web about how to access bluetooth from within a docker container. Most are complex and largely unsuccessful it seems. It turns out that it is very easy in the case of your plug-in. It just requires changing the privileges to the node file (as described) but the commands need to be executed from within the homebridge container.

FYI. The steps are:

1. Determine the path to the running node from within the homebridge container:

	docker exec -it my_hombridge_container which node

for me this returns:  /usr/local/bin/node

(this is different to the path returned by “which node” when executed outside a container!)

2. Set privileges for the returned file (might require sudo depending on user)

	docker exec -it my_hombridge_container setcap cap_net_raw+eip /usr/local/bin/node

3. Reboot 

Error message is gone and shades show instantly in the Home app.

It’s likely that the same thing could be achieved by setting up the appropriate privileges when the container is created but I don't want to go through setting up all my accessories again just to test this. The whole point of using containers is security, so the method above would seem the best option as it does not require giving unneeded privileges to the whole container.

Sorry to bug you with a false report.

**Comment by oovz** [comment]
Glad you find a solution! I think it's very good as some other users may find it useful.
