### ISSUE TITLE
Invalid services after configuring the MAC address

### ISSUE THREAD

**Issue by IamMrandrew** [fisherwise/homebridge-soma-shades#8]
**Describe Your Problem:**

I am new to this plugin. I just bought my SOMA Smart Shades 2, connected to the soma app. I failed to flash the official SOMA Connect image, and I also dont want to waste a raspberry pi just for running such services.

The problem that I encounter is that I wasn't able to add my shade to HOOBS with this plugin. I typed to following information to config, where the id is the mac address of my shades.
<img width="1103" alt="截圖 2021-05-18 23 34 06" src="https://user-images.githubusercontent.com/62586450/118680718-8c331b80-b831-11eb-8345-922d55a9f390.png">

I scan the MAC address with `sudo hcitool lescan`, use the mac address with name RISEAPP252. Is there any possible reason is that the mac address I input is wrong? 

I got a fake accessory searched, but inside log, it said invalid services.

<img width="1042" alt="截圖 2021-05-18 23 36 56" src="https://user-images.githubusercontent.com/62586450/118681151-f21fa300-b831-11eb-9538-2aac8ff773cd.png">

**Logs:**

```
2021/5/18 下午11:26:38 Got SIGINT, shutting down Bridge...
2021/5/18 下午11:26:40 Initializing HAP-NodeJS v0.9.2...
2021/5/18 下午11:26:41 Loaded plugin 'homebridge-soma-shades'
2021/5/18 下午11:26:41 [5/18/2021, 9:26:41 AM] Registering platform 'homebridge-soma-shades.SOMAShades'
2021/5/18 下午11:26:41 Loading 1 platforms...
2021/5/18 下午11:26:41 [SOMAShades] Initializing SOMAShades platform...
2021/5/18 下午11:26:41 Preparing Advertiser for 'HOOBS 65EF' using bonjour-hap backend!
2021/5/18 下午11:26:41 Starting to advertise 'HOOBS 65EF' using bonjour-hap backend!
2021/5/18 下午11:26:41 Bridge is running on port 51826.
2021/5/18 下午11:26:56 [SOMAShades] Bedroom is not configured, removing...
2021/5/18 下午11:26:56 [SOMAShades] noble is not running. waiting for it to power on...
2021/5/18 下午11:26:56 [SOMAShades] noble is powered on
2021/5/18 下午11:26:56 [SOMAShades] discovered peripheral 756caa12a791, adding to accessories
2021/5/18 下午11:26:56 [SOMAShades] discovered all peripherals
2021/5/18 下午11:26:57 [SOMAShades] peripheral 756caa12a791 has invalid services
2021/5/18 下午11:26:57 [SOMAShades] accessory Bedroom failed to get device information: Error: invalid services
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.2.0 published 1/25/2021
* **Homebridge Version**:  HOOBS Core Current Version: 3.3.3
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by IamMrandrew** [comment]
And seems like the mac address i get change from time to time. Shouldn't it be consistent?

**Comment by oovz** [comment]
your mac address could be wrong. I don't see mine with that name(but mine is ```(unknown)``` tho).
Can you try the Soma app and get mac address from there?

**Comment by IamMrandrew** [comment]
> your mac address could be wrong. I don't see mine with that name(but mine is ```(unknown)``` tho).
> 
> Can you try the Soma app and get mac address from there?

The smart shades app right? I get the serial number only, i think it is not the mac address. 

Where can i find the mac address?

**Comment by oovz** [comment]
the serial number is mac address

**Comment by IamMrandrew** [comment]
I put the serial number as mac address, but it is not working. And actually, I cant find a device with the serial number as mac address with `sudo hcitool lescan`. But that's weird cause I can pair the device with my phone, so its bluetooth should be running. Normally, I can scan the device with same mac address as the serial number right?

**Comment by IamMrandrew** [comment]
Nvm, managed to flash the official soma-connect with my extra raspberry pi. Thanks anyway

**Comment by burntcookie90** [comment]
This is still an issue btw. Using the Mac addresses from the app and I'm also receiving these errors.

**Comment by oovz** [comment]
> This is still an issue btw. Using the Mac addresses from the app and I'm also receiving these errors.

can you discover the mac address with hcitool?
